FROM maven:3.9.6-eclipse-temurin-22-alpine

RUN echo "Creating working dir and copying files"
RUN mkdir /app
WORKDIR /app
COPY . .

RUN mvn clean
RUN mvn install

CMD ["java", "-jar", "target/JavaReviewTopics-1.0.0.jar"]