FROM node:22.0

RUN echo "Creating working dir and copying files"
RUN mkdir /app
WORKDIR /app
COPY . .

RUN npm i
RUN cd async_error_node_2024 && npm i

# Will print to Docker w/ rebinding or redirecting STDOUT this way.
CMD [ "bash", "run.sh" ]